######################################################################
# V-SYNC & FULLSCREEN FIX FOR GAMES (TESTED FOR TEAM FORTRESS 2) PICOM
######################################################################
backend = "xrender";        
vsync = true;               
shadow = false;
no-dock-shadow = true;
no-dnd-shadow = true;
fading = false;
fade-delta = 0;
fade-in-step = 0.0;
fade-out-step = 0.0;
blur-method = "none";
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
opacity-rule = [];
mark-wmwin-focused = false;
mark-ovredir-focused = false;
detect-client-opacity = true;
corner-radius = 0;
unredir-if-possible = true;
log-level = "warn";
